### PR TITLE
Update istio version

### PR DESCRIPTION
**Pull request by alibazlamit**
Tested on google, azure and aws, all sub-charts are updated as well

### CODE REVIEW

**Comment by baldwinSPC** [comment]
@FranBarrera can you check this one, too, please?

**Comment by FranBarrera** [comment]
@alibazlamit values.yml doesn't seems to be fully updated, also the image tag is still 1.0.1 and it should be 1.1.0 but it is not published, it's still 1.1.0-snapshot.2

**Comment by alibazlamit** [comment]
@FranBarrera should we update isitio as found here in this repo https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio.
This looks much different from what we have now as it does not have the helm charts folder ?

**Comment by FranBarrera** [comment]
@alibazlamit Yes, we have to update it from that repo, but we have some differences about how we create and expose some addons. About the helm-charts folder, you can check in the official repo, the charts folder exists in the 1.0.1 version - https://github.com/istio/istio/tree/1.0.1/install/kubernetes/helm/istio, maybe that will change in 1.1.0

**Comment by alibazlamit** [comment]
putting this PR on hold until isitio 1.1.0 is [released](https://github.com/istio/istio/releases)

**Pull request closed without merging**
