### PR TITLE
Update OpenEBS charts version to 0.8.0

### PR DESCRIPTION
**Pull request by muratkars**
Update OpenEBS charts to the latest stable version
Updating storage engines to 0.8.0
Adding NDM support
Adding patches for MayaOnline visibility support

### CODE REVIEW

**Comment by muratkars** [comment]
This will close [2365](https://github.com/openebs/openebs/issues/2365)

**Comment by muratkars** [comment]
Tested successfully on StackPointCloud with stateful workloads

```
$ kubectl get pods -n openebs
NAME                                                        READY   STATUS    RESTARTS   AGE
cstor-sparse-pool-6eiu-567459d999-nrjgk                     2/2     Running   0          19m
cstor-sparse-pool-hpu2-766c64cb4d-cbqp7                     2/2     Running   0          19m
cstor-sparse-pool-p59s-6cdd95ffbb-zpfdp                     2/2     Running   0          18m
openebs-gentle-fashion-apiserver-5b979b6559-l2lwt           1/1     Running   0          19m
openebs-gentle-fashion-ndm-6nrjd                            1/1     Running   0          19m
openebs-gentle-fashion-ndm-9clmr                            1/1     Running   0          19m
openebs-gentle-fashion-ndm-lrkcb                            1/1     Running   0          19m
openebs-gentle-fashion-provisioner-54d7d6dd59-rt44s         1/1     Running   0          19m
openebs-gentle-fashion-snapshot-operator-7c6bcf488c-n55lj   2/2     Running   0          19m
```

**Comment by muratkars** [comment]
Hi @FranBarrera 
Could you please take a look at this PR or assign it to someone to review when you have a chance. Thanks!

**Comment by FranBarrera** [comment]
@muratkars Thanks!

**Pull request merged**
